### ISSUE TITLE
Make dashboard end user friendly and public

### ISSUE THREAD

**Issue by ylembachar** [shutter-network/shutter-explorer#1]
## Description
Develop a public UI to make Shutter information publicly available. The UI will pull data from different data sources (observer and encrypting rpc) in a secure way, and will provide insights into shutterized slots, transaction lifecycles and registered validators. 

#### Validator overview
- Number of Shutterized Validators: Total number and percentage of all validators.
- Encrypted Validators: Percentage of validators using encryption.

#### Keyper Overview
- Number of Keypers: Count of online keypers.
- Keyper Threshold: Threshold number of keypers required for operation.

#### Transaction Overview
- Total # of shutterized transactions to date
- Percentage of encrypted transactions

#### Inclusion Time Overview
- Estimated inclusion time / average time for a shutterized slot
- Historical Inclusion Time: Distribution and historical data of transaction inclusion times.
- Number of Slots/Transactions Not Included as Expected: Count of slots/transactions that failed to be included.
- Successfully Executed Transactions: Total number following the shutter protocol correctly.
- Failed Transactions: Total number that were not included as expected.

#### MEV Dashboard
- General MEV dashboard: with $ stolen, $ saved, % of shuttered transactions out of all chains

#### Slot overview
- A bar that shows the current epoch and the slot progression with the shutterized slots highlighted
- Previous shutterized slot details (Slot number, number of included transactions, number of pending transactions)

#### Decryption Key Overview
Timestamps Seen: List of timestamps when decryption keys were observed

#### Transaction Overview
- Search bar that lets a user search for a given transaction (per transaction hash or encrypted transaction hash) 
- Seen in Encrypted Mempool: Timestamp of each transaction.
- Keys Released: Slot number for each transaction.
- Preview of sequencer transactions with links to the explorer
- Preview of pending transactions / included transactions

### Page 3: Transaction Detail Page
- Search bar that lets a user search for a given transaction (per transaction hash or encrypted transaction hash)
- Transaction status (pending/included)
- Estimated/Effective inclusion time
- The list of corresponding encrypted transaction hashes with links
- The link to the included transaction if included

## Back-end
Develop a backend service to extract data from all relevant data sources while ensuring secure data access, either by exporting the data via a JSON API or by querying the relevant information from the different data sources.

## Design
Consult with the marketing team to get the graphical designs for the above interfaces.

### References
https://beaconcha.in/
https://x.com/drakefjustin/status/1801321889152835758/video/1

### List of sub-tasks / issues to create
1) Confirm with business/design teams
2) [Build the backend component](https://github.com/shutter-network/shutter-explorer/issues/2)
3) [Build the front-end component](https://github.com/shutter-network/shutter-explorer/issues/3)

**Comment by ylembachar** [comment]
Thanks for the feedback, I've updated the description with more details and checked against the items on the original EPIC. 

(Yes, search bar would lead to 3.)

**Comment by caravello00** [comment]
Quickly aligning on the call we just had with @faheelsattar @pepae @ulope (I can't seem to tag tatu)

## Engine Room/Dashboard:
- What is it: The development of an interactive dashboard, similar to https://eigenphi.io/ but for Shutters integrations
- Location: It can either be hosted on the website or a subdomain
Purpose: a destination for developers and others to peek under the hood of Shutter and its integrations to help them understand
- what is happening (with the system)
- the case for future integrations
- For initial launch 15 Sept: Develop a dashboard for Shutterized Gnosis Chain: May or may not be on a 3 separate pages - depends on the best way to display info and the future proof for additional integration dashboards
 - Future dashboards to be added to the Engine Room:
    - Shutterized Snapshot
    - Overall Shutterized MEV dashboard
    - [Future integration]
    - [Future integration]
    - [Future integration]

## Content for Gnosis Chain Dashboard:
1) Overview (e.g. # of shutterized validators, # of keypers, keyper threshold, total # of shutterized transactions to date, average time to inclusion etc.) + general MEV dashboard: with $ stolen, $ saved, % of shuttered transactions out of all chains

2) Key generation overview
- A bar that shows the current epoch and the slot progression with the shutterized slots highlighted
- Previous shutterized slot details (Slot number, number of included transactions, number of pending transactions)
- Estimated inclusion time / average time for a shutterized slot
- Preview of sequencer transactions with links to the explorer
- Preview of pending transactions / included transactions
- Search bar that lets a user search for a given transaction (per transaction hash or encrypted transaction hash) (and this links to 3 then?)

3) Transaction Detail Page
- Search bar that lets a user search for a given transaction (per transaction hash or encrypted transaction hash)
- Transaction status (pending/included)
- Estimated/Effective inclusion time
- The list of corresponding encrypted transaction hashes with links
- The link to the included transaction if included

## Design Support Needed
- Suggest domain: explorer.shutter.network
- Suggest name
- Provide overall design: e.g. colors, fonts, what the lines, bars, tabs, symbols look like, etc
- Suggest the order of content
- Suggest the overall layout and navigation, make it look similar to the website

## My proposed menu and tabs layout
- Similar to EigenPhi
- At top, menu of shutterized platforms (first would be Gnosis Chain)
- At left side, tabs see different dashboards of the shutterized gnosis chain
<img width="1133" alt="Screenshot 2024-08-19 at 5 52 30 PM" src="https://github.com/user-attachments/assets/cafe4d44-aae5-4e87-a3a4-c9d4b33b6d3a">


---

## Timeline
- TBD
- Launch 15 Sept

**Comment by caravello00** [comment]
For design development:
1. Confirm content display for the dashboard
2. Itemized list of content in a doc (with an example of what it could look like) to share with the design agency to mock up
3. Brief the agency together
4. A mock up, and design elements for each itemized list of content

**Comment by ylembachar** [comment]
Hey @caravello00, we had the meeting to confirm the content and the format and added everything under [this document.](https://docs.google.com/spreadsheets/d/1KeSPARb1oXCwdkA50R7TIoU3Qw-oRAFB_fQkwYZKFNc/edit?usp=sharing)

**Comment by caravello00** [comment]
@ylembachar thanks for this, I added several comments, let's jump on a call when you're online, and schedule a chat with the vendor today.

**Comment by caravello00** [comment]
@ylembachar (I still can't tag tatu) we need a few more details about the design work for development:
- Does it need to be delivered in a specific design file? Is it flexible?
- Does the design need to be pixel-perfect for the developer to literally create exactly the same? Or is it just a representation for the developer to create the page based on it?
- Does the developer literally need a design for each of the modules and contents within it? Or do we just need a design for the difference types of content, then the developer can create the content based on the reference and change relevant info?

**Comment by ylembachar** [comment]
@caravello00 Questions answered during our call. You can tag Tatu now.
