### ISSUE TITLE
Update transaction status design

### ISSUE THREAD

**Issue by ylembachar** [shutter-network/shutter-explorer#200]
Update the transaction status design to conform with the Figma design shown below:

The statuses need capitalization, a bigger font, and the colors to conform with the design

<img width="479" alt="Screenshot 2024-10-28 at 14 55 50" src="https://github.com/user-attachments/assets/71ac0e63-5318-42c1-9c05-1ba5aee30393">

**Comment by faheelsattar** [comment]
i think the colors for the statuses which are same as in the design are correct, the ones which have introduced/newer ones are different which isnt defined in the design

**Comment by ylembachar** [comment]
> i think the colors for the statuses which are same as in the design are correct, the ones which we have introduced/newer ones are different which isn't defined in the design

Yes, we just need to make sure that the color of the text is a bolder shade of the background color, or a darker color in the event of yellow statuses. We also need to increase the font-size as it's now smaller than in the design. I would also change the unshielded inclusion to a darker color so that the text is clearer.

<img width="141" alt="Screenshot 2024-10-29 at 13 24 07" src="https://github.com/user-attachments/assets/aa7d1cf3-3560-4f39-8605-32bca2b0fc7c">
